# Generated by Django 5.2.3 on 2025-06-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[("Men", "Men"), ("Women", "Women"), ("Kids", "Kids")],
                        max_length=10,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        choices=[("Topwear", "Topwear"), ("Bottomwear", "Bottomwear")],
                        max_length=20,
                    ),
                ),
                ("sizes", models.JSONField(default=list)),
                ("date", models.DateTimeField()),
                ("bestseller", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
