# Generated by Django 5.2.3 on 2025-09-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['product', 'size'], name='product_pro_product_0c0c8a_idx'),
        ),
    ]
