# Generated by Django 5.2.3 on 2025-06-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_sizes_productimage_alt_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
    ]
