# Generated by Django 5.2.3 on 2025-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("manager", "Manager")],
                default="manager",
                max_length=20,
            ),
        ),
    ]
