# Generated by Django 5.2.3 on 2025-06-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_managers_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="movies/"),
        ),
    ]
