# Generated by Django 5.2.3 on 2025-07-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_address"),
        ("orderItem", "0001_initial"),
        ("product", "0003_remove_productimage_alt_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ordered_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="payment_intent_id",
            new_name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price_at_purchase",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
