# Generated by Django 5.2.3 on 2025-06-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product",
            new_name="product_id",
        ),
    ]
